#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
echo "Rodando Larastan...";
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
#    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;

# rodar os testes
echo "Rodando testes...";
 # Executa os testes
    php artisan test --parallel

    # Verifica o código de saída dos testes
    if [ $? -ne 0 ]; then
#        echo "Erro: Ocorreram erros nos testes. Corrija-os antes de fazer o commit."
        exit 1
    fi

# Formatar cada arquivo alterado usando o Laravel Pint
echo "Formatando cada arquivo alterado usando o Laravel Pint...";
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}";
    #./vendor/bin/pint "${FILE}" > /dev/null >&1; não mostrar as mensagens
    git add "${FILE}";
done;

echo "Sucesso! Comitando..."

exit 0;
